# Supabase Project Configuration
project_id = "elepidjpvuywldsnaetd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://facepay-kappa.vercel.app"]

[edge_functions]
enabled = true
